sudo: required
language: node_js
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
services:
  - docker 
node_js:
  - 4.1.1
before_script:
  - npm install -g grunt-cli
after_success:
  - export REPO=jlikness/docker-contain-mcc
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker login -u $DOCKER_USER -p $DOCKER_PASS https://hub.docker.com
  - docker push $REPO
